name: "godot-ci export"
on:
  push:
    branches:
    - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: MediaCoverRecap
  PROJECT_PATH: ./MediaCoverRecap

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          lfs: true
      - name: Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls ~/.local/share/godot/export_templates/
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup folders
        run: |
          mkdir -p .godot/editor .godot/imported
          mkdir -v -p build/windows
          mkdir -v -p build/web
          mkdir -v -p build/linux
      - name: Web Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Web" ../build/web/index.html
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Linux Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Linux" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: my-builds
          path: build
  release-itchio:
    name: To itchio
    needs: build  
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Download build 
        uses: actions/download-artifact@v4.1.8
        with:
          name: my-builds
      - name: Upload bundles
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          echo $GITHUB_REF_NAME
          butler push web $ITCH_USER/$ITCH_GAME:html5 --userversion $GITHUB_REF_NAME
          butler push windows $ITCH_USER/$ITCH_GAME:windows --userversion $GITHUB_REF_NAME
          butler push linux $ITCH_USER/$ITCH_GAME:linux --userversion $GITHUB_REF_NAME
